baseURL = 'https://masoud-heidary.ir/'
languageCode = 'en-us'
title = 'Masoud'
theme = 'terminal'
pagination.pagerSize = 5
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  showLanguageSelector = true
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  # updatedDatePrefix = "Updated"
  readingTime = false
  # Toc = false   # table of content
  # TocTitle = false
  # dateFormat = "2006-01-02 3:04:06 PM MST"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Masoud"
    copyright = "Masoud/ blog powered by Hugo & panr theme"

    [languages.en.params]
      subtitle = "personal blog"
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      # newerPosts = "Newer posts"
      # olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      # inuteReadingTime = "min read"
      # words = "words"

    [languages.en.params.logo]
      logoText = "Masoud"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume"
